package opam

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/emilkloeden/oc/internal/project"
)

func Generate(dir string, cfg *project.Config) error {
	var b strings.Builder

	synopsis := cfg.Project.Synopsis
	if synopsis == "" {
		synopsis = "A new OCaml project"
	}

	b.WriteString("# This file is generated by oc. Do not edit.\n")
	b.WriteString("opam-version: \"2.0\"\n")
	fmt.Fprintf(&b, "name: %q\n", cfg.Project.Name)
	fmt.Fprintf(&b, "version: %q\n", cfg.Project.Version)
	maintainer := cfg.Project.Maintainer
	if maintainer == "" {
		maintainer = "Unknown"
	}
	fmt.Fprintf(&b, "synopsis: %q\n", synopsis)
	fmt.Fprintf(&b, "maintainer: %q\n", maintainer)
	if len(cfg.Project.Authors) > 0 {
		b.WriteString("authors: [")
		for i, a := range cfg.Project.Authors {
			if i > 0 {
				b.WriteString(" ")
			}
			fmt.Fprintf(&b, "%q", a)
		}
		b.WriteString("]\n")
	}
	if cfg.Project.Homepage != "" {
		fmt.Fprintf(&b, "homepage: %q\n", cfg.Project.Homepage)
	}
	if cfg.Project.BugReports != "" {
		fmt.Fprintf(&b, "bug-reports: %q\n", cfg.Project.BugReports)
	}
	if cfg.Project.License != "" {
		fmt.Fprintf(&b, "license: %q\n", cfg.Project.License)
	}
	b.WriteString("depends: [\n")

	// ocaml and dune are always required
	fmt.Fprintf(&b, "  \"ocaml\" {>= %q}\n", cfg.OCaml.Version)
	b.WriteString("  \"dune\" {>= \"3.0\"}\n")

	for _, name := range sortedKeys(cfg.Dependencies) {
		constraint := cfg.Dependencies[name]
		b.WriteString("  ")
		b.WriteString(depLine(name, constraint, ""))
		b.WriteString("\n")
	}
	for _, name := range sortedKeys(cfg.DevDependencies) {
		constraint := cfg.DevDependencies[name]
		b.WriteString("  ")
		b.WriteString(depLine(name, constraint, " {with-test}"))
		b.WriteString("\n")
	}

	b.WriteString("]\n")

	path := filepath.Join(dir, cfg.Project.Name+".opam")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func depLine(name, constraint, suffix string) string {
	if constraint == "*" || constraint == "" {
		return fmt.Sprintf("%q%s", name, suffix)
	}
	// convert >=X.Y.Z → {>= "X.Y.Z"}
	opam := convertConstraint(constraint)
	return fmt.Sprintf("%q %s%s", name, opam, suffix)
}

func convertConstraint(c string) string {
	for _, op := range []string{">=", "<=", ">", "<", "="} {
		if strings.HasPrefix(c, op) {
			ver := strings.TrimSpace(strings.TrimPrefix(c, op))
			return fmt.Sprintf("{%s %q}", op, ver)
		}
	}
	return fmt.Sprintf("{= %q}", c)
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
