package opam_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/emilkloeden/oc/internal/opam"
	"github.com/emilkloeden/oc/internal/project"
)

func cfg(name string, deps, devDeps map[string]string) *project.Config {
	return &project.Config{
		Project:         project.ProjectMeta{Name: name, Version: "0.1.0"},
		OCaml:           project.OCamlMeta{Version: "5.2.0"},
		Dependencies:    deps,
		DevDependencies: devDeps,
	}
}

func TestGenerate_CreatesFile(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{"cohttp": ">=5.0.0"}, map[string]string{})

	if err := opam.Generate(dir, c); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	path := filepath.Join(dir, "my_app.opam")
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected %s to exist: %v", path, err)
	}
}

func TestGenerate_ContainsHeader(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "# This file is generated by oc. Do not edit.") {
		t.Error("missing do-not-edit header")
	}
}

func TestGenerate_IncludesDependencies(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{
		"cohttp": ">=5.0.0",
		"lwt":    ">=5.7.0",
	}, map[string]string{})
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, `"cohttp"`) {
		t.Error("missing cohttp dependency")
	}
	if !strings.Contains(content, `{>= "5.0.0"}`) {
		t.Error("missing cohttp version constraint")
	}
	if !strings.Contains(content, `"lwt"`) {
		t.Error("missing lwt dependency")
	}
}

func TestGenerate_IncludesDevDependencies(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{
		"alcotest": "*",
	})
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, `"alcotest"`) {
		t.Error("missing alcotest dev-dep")
	}
	if !strings.Contains(content, `{with-test}`) {
		t.Error("alcotest should be marked with-test")
	}
}

func TestGenerate_OCamlVersionConstraint(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, `"ocaml"`) {
		t.Error("missing ocaml dep")
	}
	if !strings.Contains(content, `{>= "5.2.0"}`) {
		t.Error("missing ocaml version constraint")
	}
}

func TestGenerate_WildcardConstraint(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{"lwt": "*"}, map[string]string{})
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	// "*" means no constraint — should just appear as "lwt" with no version filter
	if !strings.Contains(content, `"lwt"`) {
		t.Error("missing lwt")
	}
}

func TestGenerate_IncludesDune(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, `"dune"`) {
		t.Error("dune should always be listed as a build dep")
	}
}

func TestGenerate_IncludesSynopsis(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	c.Project.Synopsis = "A great OCaml app"
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "A great OCaml app") {
		t.Error("missing synopsis")
	}
}

func TestGenerate_DefaultSynopsis(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "synopsis:") {
		t.Error("synopsis field should always be present")
	}
}

func TestGenerate_DefaultMaintainer(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	// maintainer left empty
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "maintainer:") {
		t.Error("maintainer field should always be present")
	}
}

func TestGenerate_IncludesMaintainer(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	c.Project.Maintainer = "Alice <alice@example.com>"
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "alice@example.com") {
		t.Error("missing maintainer")
	}
}

func TestGenerate_IncludesAuthors(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	c.Project.Authors = []string{"Alice <a@b.com>"}
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "Alice <a@b.com>") {
		t.Error("missing authors field")
	}
}

func TestGenerate_IncludesHomepage(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	c.Project.Homepage = "https://github.com/alice/my_app"
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "https://github.com/alice/my_app") {
		t.Error("missing homepage field")
	}
}

func TestGenerate_IncludesBugReports(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	c.Project.BugReports = "https://github.com/alice/my_app/issues"
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "https://github.com/alice/my_app/issues") {
		t.Error("missing bug-reports field")
	}
}

func TestGenerate_IncludesLicense(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	c.Project.License = "MIT"
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if !strings.Contains(content, "MIT") {
		t.Error("missing license field")
	}
}

func TestGenerate_OmitsAuthorsWhenEmpty(t *testing.T) {
	dir := t.TempDir()
	c := cfg("my_app", map[string]string{}, map[string]string{})
	// Authors left nil/empty
	if err := opam.Generate(dir, c); err != nil {
		t.Fatal(err)
	}

	content := readFile(t, filepath.Join(dir, "my_app.opam"))
	if strings.Contains(content, "authors:") {
		t.Error("authors: field should not be present when authors is empty")
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("readFile %s: %v", path, err)
	}
	return string(b)
}
