package project_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/emilkloeden/oc/internal/project"
)

func TestDetect_DuneManaged(t *testing.T) {
	dir := t.TempDir()
	content := "(lang dune 3.0)\n(generate_opam_files true)\n\n(package\n (name my_app))\n"
	if err := os.WriteFile(filepath.Join(dir, "dune-project"), []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	pt, err := project.Detect(dir)
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}
	if pt != project.TypeDuneManaged {
		t.Errorf("got %v, want TypeDuneManaged", pt)
	}
}

func TestDetect_HandWrittenOpam(t *testing.T) {
	dir := t.TempDir()
	// dune-project exists but without generate_opam_files
	if err := os.WriteFile(filepath.Join(dir, "dune-project"), []byte("(lang dune 3.0)\n"), 0644); err != nil {
		t.Fatal(err)
	}
	// hand-written .opam file
	opamContent := "opam-version: \"2.0\"\nname: \"my_app\"\ndepends: [ \"ocaml\" \"dune\" ]\n"
	if err := os.WriteFile(filepath.Join(dir, "my_app.opam"), []byte(opamContent), 0644); err != nil {
		t.Fatal(err)
	}

	pt, err := project.Detect(dir)
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}
	if pt != project.TypeHandWrittenOpam {
		t.Errorf("got %v, want TypeHandWrittenOpam", pt)
	}
}

func TestDetect_OnlyOpamFile(t *testing.T) {
	dir := t.TempDir()
	opamContent := "opam-version: \"2.0\"\nname: \"my_lib\"\ndepends: [ \"ocaml\" ]\n"
	if err := os.WriteFile(filepath.Join(dir, "my_lib.opam"), []byte(opamContent), 0644); err != nil {
		t.Fatal(err)
	}

	pt, err := project.Detect(dir)
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}
	if pt != project.TypeHandWrittenOpam {
		t.Errorf("got %v, want TypeHandWrittenOpam", pt)
	}
}

func TestDetect_ErrorWhenNoProject(t *testing.T) {
	dir := t.TempDir()
	_, err := project.Detect(dir)
	if err == nil {
		t.Fatal("expected error when no project files found")
	}
}

func TestDetect_PrefersduneManaged_WhenBothPresent(t *testing.T) {
	dir := t.TempDir()
	// dune-project with generate_opam_files
	content := "(lang dune 3.0)\n(generate_opam_files true)\n\n(package\n (name my_app))\n"
	if err := os.WriteFile(filepath.Join(dir, "dune-project"), []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	// also has a .opam file (generated by dune)
	opamContent := "opam-version: \"2.0\"\nname: \"my_app\"\n"
	if err := os.WriteFile(filepath.Join(dir, "my_app.opam"), []byte(opamContent), 0644); err != nil {
		t.Fatal(err)
	}

	pt, err := project.Detect(dir)
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}
	if pt != project.TypeDuneManaged {
		t.Errorf("got %v, want TypeDuneManaged", pt)
	}
}
